#!/bin/sh
# jassi - A Simple and Robust JavaScript Lexer
# Copyright 2011 (c) Konrad Rieck (konrad@mlsec.org)

export PATH=/opt/local/bin:$PATH:/usr/local/bin

ACLOCAL=aclocal
AUTOHEADER=autoheader
AUTOMAKE=automake
AUTOCONF=autoconf
LIBTOOLIZE=glibtoolize

rm -f aclocal.m4
rm -f m4/lib* m4/lt*
mkdir -p m4

echo "Autotools"
echo " + aclocal..."     && $ACLOCAL -I m4 && \
echo " + libtoolize..."  && $LIBTOOLIZE --force --copy && \
echo " + autoheader..."  && $AUTOHEADER -f  && \
echo " + automake..."    && $AUTOMAKE --foreign --add-missing --copy && \
echo " + autoconf..."    && $AUTOCONF

echo "Bootstrap complete"
exit
